language: objective-c
osx_image: xcode8
env:
  before_install:
    - gem install xcpretty
  global:
    - PROJECT="FluentConstraints.xcodeproj"
    - SCHEME="FluentConstraints"
    - SDK="iphonesimulator10.0"
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 5"
    - DESTINATION="OS=9.1,name=iPhone 5s"
    - DESTINATION="OS=8.4,name=iPhone 5"
    - DESTINATION="OS=8.4,name=iPhone 5s"
script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" test | xcpretty -c
