language: objective-c
osx_image: xcode11
env:
  before_install:
    - gem install xcpretty
  global:
    - PROJECT="FluentConstraints.xcodeproj"
    - SCHEME="FluentConstraints"
    - SDK="iphonesimulator13.0"
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6"
    - DESTINATION="OS=10.3.1,name=iPhone 6"
    - DESTINATION="OS=11.0,name=iPhone 6"
    - DESTINATION="OS=12.0,name=iPhone 6"
    - DESTINATION="OS=13.0,name=iPhone 6"
script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" test | xcpretty -c
