language: objective-c
osx_image: xcode7.1
env:
  global:
    - WORKSPACE="FluentConstraints.xcworkspace"
    - SCHEME="FluentConstraints"
    - SDK="iphonesimulator9.1"
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 5"
    - DESTINATION="OS=9.1,name=iPhone 5s"
    - DESTINATION="OS=8.4,name=iPhone 5"
    - DESTINATION="OS=8.4,name=iPhone 5s"
script:
  - xctool -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" test
