language: objective-c
osx_image: xcode12
env:
  before_install:
    - gem install xcpretty
  global:
    - PROJECT="FluentConstraints.xcodeproj"
    - SCHEME="FluentConstraints"
    - SDK="iphonesimulator14.0"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone 8"
    - DESTINATION="OS=12.2,name=iPhone 8"
    - DESTINATION="OS=13.0,name=iPhone 11"
    - DESTINATION="OS=14.0,name=iPhone 11"
script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" test | xcpretty -c
